# Generated by Django 6.0.6 on 2026-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_variation'),
        ('store', '0004_alter_variation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, related_name='variations', to='store.variation'),
        ),
    ]
